### ISSUE TITLE
Problem finishing char bazaar

### ISSUE THREAD

**Issue by rokamdev** [opentibiabr/myaac#101]
### Priority

High

### Area

System

### What OS are you seeing the problem on?

Linux

### Browser

Chrome, Firefox, Edge, Opera, Safari, Other

### What happened?

When the character's time in the bazaar ends, the offer is changed to finished, however the player table and myacc_bazaar are not changed, the character does not have his account_new defined, status is not changed either.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elsongabriel** [comment]
we already have issue about char bazaar opened.
