### ISSUE TITLE
Donate via PIX

### ISSUE THREAD

**Issue by minancora** [opentibiabr/myaac#119]
### Priority

Critical

### Area

Plugins

### What OS are you seeing the problem on?

Windows

### Browser

Chrome

### What happened?

Ao comprar Coin via pix ele encaminha pra página de sucesso na compra e caso fique dando Refresh (F5) ele continua enviando Coin pra Table do Player.

OBS: Bug descoberto por um grupo do WhatsApp de OTServer e ninguém teve capacidade ou quis reportar.
 Não é específico do Windows ou navegador Chrome.

![Screenshot_20240905-193748_WhatsApp](https://github.com/user-attachments/assets/fa1f64ba-56d2-41bd-b696-bf613f978498)
![IMG-20240905-WA0036](https://github.com/user-attachments/assets/eddb214d-1401-4598-ac1a-336fd46828b5)
![Screenshot_20240905-193811_WhatsApp](https://github.com/user-attachments/assets/557e9a44-8d31-4b7c-81c9-3a2eb8764e4b)
![Screenshot_20240905-193818_WhatsApp](https://github.com/user-attachments/assets/d22b4ac6-943b-4c2c-9a7a-bf70feac073d)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by minancora** [comment]
Someone reported on a WhatsApp Group that if you buy Coins via pix and the purchase is sucesfull you can stay on the page pressing Refresh (F5) you can add infinite coin via player Table.

**Comment by elsongabriel** [comment]
First! This payment is not implemented on myaac yet!
