### ISSUE TITLE
Suggestion about repo (move into templates)

### ISSUE THREAD

**Issue by slawkens** [opentibiabr/myaac#14]
### Priority

Suggestion

### Area

Templates

### What is missing?

Hello,

I didn't knew where to post this suggestion, decided to post in issues, sorry if that's not the correct place.

So, what is my suggestion?

It would be much better if you create just your own template (templates/tibiacom) repository, because most of your repo changes are just appearance changes.

I compared your repo with original myaac, and it seems valid.

You can just copy all *.html.twig files and put into templates/tibiacom and they will be overwritten as myaac reads them.
The all custom pages you have - like baazar can be also put in templates under pages/ directory.

For the rest files, that are changed, we can together bring them into original myaac repo.

Let me know what do you guys think.

I think it will be better for our eco-system ;) 

There is also myaac 0.9 on the way, so you won't need to update everything manually.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elsongabriel** [comment]
@slawkens We appreciate your suggestion. But our focus and goal is to structurally organize all classes in the project. Today there is a lot of repetitive functionality, which can be improved by creating a data interface, to direct calls to existing functions, in one place. And also other improvements including development patterns etc.
