### ISSUE TITLE
admin change town character

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/myaac#28]
### Priority

Low

### Area

Admin

### What OS are you seeing the problem on?

Windows

### Browser

Opera

### What happened?

do you know why in aac, when i want to edit a character, i can't see any city, even though when i create a character, it chooses the city correctly and i can log in normally

https://prnt.sc/SIXy8c-IbhEb

https://prnt.sc/Vmjuwsg9lI1I

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elsongabriel** [comment]
already fixed:
![image](https://github.com/opentibiabr/myaac/assets/7812282/ce1d72c2-7870-4c95-90f8-f2e8e27b7718)
