### ISSUE TITLE
 Call to undefined function isVipSystemEnabled()

### ISSUE THREAD

**Issue by odisk777** [opentibiabr/myaac#36]
### Priority

Medium

### Area

Install, System

### What OS are you seeing the problem on?

Linux

### Browser

Firefox

### What happened?

I decided to migrate to updated myaac but it gives this error I am using the latest canary 3.0 version.

in config.lua is declared the "VipSystemEnable".

![imagen](https://github.com/opentibiabr/myaac/assets/65802862/fdb10008-650d-43be-a868-ff65c2006b9a)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elsongabriel** [comment]
Do you have tried update your repository? We have this function globaly created.
I've installed many times, and haven't problem. 😢

**Comment by odisk777** [comment]
> Do you have tried update your repository? We have this function globaly created. I've installed many times, and haven't problem. 😢

I am downloading it directly from github there is no other way or yes ?

**Comment by elsongabriel** [comment]
> > Do you have tried update your repository? We have this function globaly created. I've installed many times, and haven't problem. 😢
> 
> I am downloading it directly from github there is no other way or yes ?

I will check. thanks for report.

**Comment by elsongabriel** [comment]
@odisk777 Do you have `require_once SYSTEM . 'functions.php';` in your `myaac/index.php` ?
line 29.

**Comment by odisk777** [comment]
> @odisk777 Do you have `require_once SYSTEM . 'functions.php';` in your `myaac/index.php` ? line 29.

if you make a web site you don't make it as a sub folder but as the main index ????

**Comment by elsongabriel** [comment]
I redid the entire installation process and did not have this error.
