### ISSUE TITLE
Can't find config.lua while in /install

### ISSUE THREAD

**Issue by caiomdrs** [opentibiabr/myaac#41]
### Priority

Critical

### Area

Install

### What OS are you seeing the problem on?

Linux

### Browser

Firefox

### What happened?

I can't set my Server Path while install.

The form and error: 
![image](https://github.com/opentibiabr/myaac/assets/62369457/b1c78598-a0c7-4b63-8fd9-723a403f10b9)

and my CLI of server:
![image](https://github.com/opentibiabr/myaac/assets/62369457/b4476a10-6f7c-4956-aff4-0fc5b735395f)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by majestyotbr** [comment]
https://docs.opentibiabr.com/opentibiabr/projects/canary/getting-started/linux/linux-canary-+-nginx-+-mysql-+-myaac

**Comment by caiomdrs** [comment]
@majestyotbr could help me? i have been followed the tutorial, but, when i tried to submit the form on /install/, he can't load my server path, where is in /root/canary

**Comment by majestyotbr** [comment]
> @majestyotbr could help me? i have been followed the tutorial, but, when i tried to submit the form on /install/, he can't load my server path, where is in /root/canary

The issue tracker is not a support forum, use [Discord](https://discord.gg/gvTj5sh9Mp) instead.
