### ISSUE TITLE
createcharacterauction error Cannot use object of type PDOStatement as array

### ISSUE THREAD

**Issue by santosxxt** [opentibiabr/myaac#5]
When going to create a sale of a character in step 2 it is giving the error Exception class: Error() Cannot use object of type PDOStatement as array place in the code where I am doing the tests
$getCharacter = $db->query('SELECT `id`, `account_id`, `name`, `level`, `vocation`' . 'FROM `players`' . 'WHERE `id` = ' . $db- >quote($selectCharacter) .'');
$getCharacter = $getCharacter->fetch();

**Comment by elsongabriel** [comment]
for me here, it was normal, it didn't give this error.

![image](https://github.com/opentibiabr/myaac/assets/7812282/72f0a9c3-d4a4-4d86-ac2d-1b3076d158e1)

**Comment by santosxxt** [comment]
what version of php are you using?
