### ISSUE TITLE
Event Calendar

### ISSUE THREAD

**Issue by whitecrixu** [opentibiabr/myaac#53]
### Priority

Low

### Area

System

### What OS are you seeing the problem on?

Linux

### Browser

Chrome, Firefox, Edge, Opera, Safari

### What happened?

This page isn’t working 127.0.0.1  is currently unable to handle this request.
HTTP ERROR 500 when i try get acces to event

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elsongabriel** [comment]
No explanation of the issue! Error 500 is a server error or bad config.
