### ISSUE TITLE
XSS in bugtracker

### ISSUE THREAD

**Issue by slawkens** [opentibiabr/myaac#55]
### Priority

Critical

### Area

System

### What OS are you seeing the problem on?

Linux, Windows, MacOS

### Browser

Chrome, Other

### What happened?

Hi,

Just to let you know: there has been more security vulnerabilities found in bugtracker. (XSS)

I reviewed the file fully now, and patched the changes here:
https://github.com/slawkens/myaac/commit/ee32384dcadbaec678e69449ad33d439eb9de13a

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by elsongabriel** [comment]
So thanks. <3
Sync's PR created.
