### ISSUE TITLE
Characters

### ISSUE THREAD

**Issue by caduhsn** [opentibiabr/myaac#57]
### Priority

Low

### Area

System

### What OS are you seeing the problem on?

Linux

### Browser

Opera

### What happened?

Quando acesso a pagina de characters (seleciono o perfil do personagem) a pagina responde em branco sem informações.
Não me da nenhum erro apenas fica em branco.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elsongabriel** [comment]
Já tentei de diversas formas, e está tudo OK.
acredito que no momento da instalação pode ter dado algo errado, por isso está faltando aquela table.
tente refazer o processo de instalação do myaac e tente novamente.
