### ISSUE TITLE
Eventcalendar error

### ISSUE THREAD

**Issue by caduhsn** [opentibiabr/myaac#58]
### Priority

Low

### Area

System

### What OS are you seeing the problem on?

Linux

### Browser

Chrome

### What happened?

O calendário de eventos não está abrindo, verifiquei no log de erros e apareceu a seguinte mensagem..
`2023/12/20 09:21:45 [error] 817#817: *25842 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home/www/system/pages/eventcalendar.php on line 96" while reading response header from upstream, client: 'xxx.xxx..ipclient', server: _, request: "GET /?eventcalendar HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "ipserver", referrer: "http://ipserver/"
`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luancolombo** [comment]
Procure na linha 95 o seguinte: for($i = 0; $i < 7; $i++)
	 echo "<td>".$semanas{$i}."</td>";
	 
substitua apenas os simbolos para ficar assim	<td>".$semanas[$i]."</td>";
