### ISSUE TITLE
Event calendar wrong days

### ISSUE THREAD

**Issue by Sorairei** [opentibiabr/myaac#61]
### Priority

Low

### Area

System

### What OS are you seeing the problem on?

Linux

### Browser

Chrome

### What happened?

anyone can help me to check this one? event calendar wrong date one day ahead, today is **Thursday 11**, in page shows **Friday 11**.

![image](https://github.com/opentibiabr/myaac/assets/79299476/67dce0e9-3be6-4771-b241-232d2de808b7)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by caduhsn** [comment]
verificou a data da sua maquina?
