### ISSUE TITLE
Boosted creature

### ISSUE THREAD

**Issue by caduhsn** [opentibiabr/myaac#66]
### Priority

Medium

### Area

System, Templates

### What OS are you seeing the problem on?

Linux, Windows

### Browser

Opera

### What happened?

Algumas imagens estão saindo estourada no pedestal de creaturas boostadas do dia.

![image](https://github.com/opentibiabr/myaac/assets/148654410/784fdafd-bb37-4e2f-ba81-fcb6a7674e5c)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elsongabriel** [comment]
pelo visto, você está usando um pedestal custom. acredito ter visto isso acontecer. vou checar aqui para ajustar o tamanho, mas tudo indica que pode ser que venha do animated outfit.

**Comment by caduhsn** [comment]
> pelo visto, você está usando um pedestal custom. acredito ter visto isso acontecer. vou checar aqui para ajustar o tamanho, mas tudo indica que pode ser que venha do animated outfit.

eu ja fui verificar o tamanho da imagem nos arquivos de animação e está normal.

Na vez que verifiquei foi a **Banshee** ela é um dos vários que estão estourando.

**Comment by caduhsn** [comment]
Sabe quando arrumaram isso ?
