### ISSUE TITLE
vulnerability !!!

### ISSUE THREAD

**Issue by tomasz1337** [opentibiabr/myaac#67]
### Priority

Critical

### Area

System

### What OS are you seeing the problem on?

Linux, Windows

### Browser

Chrome

### What happened?

XSS vulnerability IN HIGHSCORES.PHP INPUT VOCATION!!!!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by luancolombo** [comment]
Temos essas soluções mas nao to sabendo como aplicar para o site todo, consegue ajudar @elsongabriel ?
https://pt.linux-console.net/?p=20645
