### ISSUE TITLE
myaac. characters.php error

### ISSUE THREAD

**Issue by daniofordon** [opentibiabr/myaac#72]
### Priority

High

### Area

Templates

### What OS are you seeing the problem on?

Linux

### Browser

Edge

### What happened?

Hello. After installing Canary 13.32 and the current MyAAC. Everything is ok. But when I want to search for a character in the search engine, it redirects me to a blank page.

https://prnt.sc/nks0H49PNX6W

when I fire up the developer mode, it pops up

https://prnt.sc/AAkQNLfmKv1j

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by daniofordon** [comment]
I forgot to add. All on Debian 12 and PHP 8.2

**Comment by majestyotbr** [comment]
If you tried to search about bcdiv(), it's missing php-bcmath in your system.

sudo apt install php8.2-bcmath

Next time, follow a tutorial on gitbook:
https://docs.opentibiabr.com/opentibiabr/projects/canary/getting-started/linux/linux-canary-+-nginx-+-mariadb-+-myaac
