### ISSUE TITLE
Problem with account creation

### ISSUE THREAD

**Issue by Uhahny** [opentibiabr/myaac#77]
### Priority

Low

### Area

System

### What OS are you seeing the problem on?

Linux

### Browser

Chrome

### What happened?

The Following Errors Have Occurred:
Wrong characters configuration. Try again or contact with admin. ADMIN: Edit file config.php and set valid characters to copy names. Character to copy: Druid Sample doesn't exist.

canfig php is original from github i try to update vocations.xml and after this happend

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elsongabriel** [comment]
you need to import canary "schema.sql" file first.
