### ISSUE TITLE
Error login on account

### ISSUE THREAD

**Issue by Nazgul001** [opentibiabr/myaac#78]
### Priority

Low

### Area

System

### What OS are you seeing the problem on?

Windows

### Browser

Opera

### What happened?

Error when trying to enter to account..

http://127.0.0.1/?account/manage

manage page dosent exit

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elsongabriel** [comment]
I've made a login, and working fine.
![image](https://github.com/opentibiabr/myaac/assets/7812282/aebc33f6-4a70-4726-972b-fe91da2d3c92)
