### ISSUE TITLE
http://127.0.0.1:8080/login.php showing error

### ISSUE THREAD

**Issue by GutoSalvador** [opentibiabr/myaac#81]
### Priority

Low

### Area

System

### What OS are you seeing the problem on?

Windows

### Browser

Chrome

### What happened?

The message showing on browser:

{"errorCode":3,"errorMessage":"Unrecognized event ."}

What to do next?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lukash10** [comment]
Alguma correção? Mesmo erro.
