### ISSUE TITLE
page title erros

### ISSUE THREAD

**Issue by antonioaraujo664** [opentibiabr/myaac#9]
title image does not load

PAGE: ?subtopic=downloadclient&step=downloadagreement

![image](https://github.com/opentibiabr/myaac/assets/16484533/976a9170-2fd0-4e7d-aba6-6282e171d0a8)

PAGE: downloadclient.php
![image](https://github.com/opentibiabr/myaac/assets/16484533/3aea5fa0-52e9-4171-aded-dc4992b03ec6)

OS: UBUNTU 22.04 SERVER
Tested: Apache end Ngnix

**Comment by SRNT-GG** [comment]
Can you turn on Devmode and see if it's showing any error it find headline.php? It could be a pathing issue, as these texts are generated by that file. Some are static images, but most are not.

**Comment by antonioaraujo664** [comment]
enabled dev mode in config.local.php
did not show any error on the page

**Comment by antonioaraujo664** [comment]
UPDATED

**Comment by antonioaraujo664** [comment]
page: bugtracker
![image](https://github.com/opentibiabr/myaac/assets/16484533/2aed2482-b4f2-4a05-b225-1c7098a25bf3)

Page: currentcharactertrades ... char bazaar etc.
![image](https://github.com/opentibiabr/myaac/assets/16484533/449b5b19-c6c4-41b4-a8f7-ada88e1575f1)

**Comment by elsongabriel** [comment]
Estou na main do myaac:
![image](https://github.com/opentibiabr/myaac/assets/7812282/5a4d9cd1-7738-40cf-b500-587fb1942a93)
![image](https://github.com/opentibiabr/myaac/assets/7812282/16d8ffe6-1a37-4b6f-8d2a-dab0bf741ef8)

**Comment by antonioaraujo664** [comment]
testei tudo do zero apache 2.4.57, ubuntu 22.04 server. O problema insiste. Seria interessante alguém com algum myaac em linux em produção verificar, vou ver se acho algum aqui no otlist

**Comment by elsongabriel** [comment]
> testei tudo do zero apache 2.4.57, ubuntu 22.04 server. O problema insiste. Seria interessante alguém com algum myaac em linux em produção verificar, vou ver se acho algum aqui no otlist

meu servidor de teste, está em uma máquina ubuntu, utilizando nginx. e não apresenta erros.

**Comment by elsongabriel** [comment]
> page: bugtracker ![image](https://user-images.githubusercontent.com/16484533/244608564-2aed2482-b4f2-4a05-b225-1c7098a25bf3.png)
> 
> Page: currentcharactertrades ... char bazaar etc. ![image](https://user-images.githubusercontent.com/16484533/244609000-449b5b19-c6c4-41b4-a8f7-ada88e1575f1.png)

char bazar PR #7 você pode nos ajudar a testar
