### ISSUE TITLE
recaptcha in login 

### ISSUE THREAD

**Issue by odisk777** [opentibiabr/myaac#98]
### Priority

Missing Content

### Area

System, Templates

### What is missing?

Recaptcha can be implemented for login system to avoid simultaneous login queries. 

![imagen](https://github.com/opentibiabr/myaac/assets/65802862/b6c9c65e-9567-4b98-937e-6f1eb2308c10)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elsongabriel** [comment]
You need to configure it in config.php or config.local.php

**Comment by odisk777** [comment]
> You need to configure it in config.php or config.local.php

could you tell me what to configure? because i have been looking and there is nothing. only the recaptcha is for the registration and not for the login.
