### ISSUE TITLE
Erro após instalação.

### ISSUE THREAD

**Issue by lukash10** [opentibiabr/myaac#99]
### Priority

High

### Area

Install

### What OS are you seeing the problem on?

Linux

### Browser

Chrome, Edge

### What happened?

Após instalar, o próprio install solicita para deletar a pasta e o config.local.php...
Mas se deletar o config.local.php, não abre mais.

Além disso problema no login.php... não abre e não funciona =c

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by elsongabriel** [comment]
Primeiramente você está criando uma issue para um problema que não existe, para isso, você deveria usar o nosso Discord para pedir suporte. E sempre que criar issue use o idioma inglês como padrão!

Outra coisa, você precisa checar as permissões da pasta. Ele informa q se você estiver tentando instalar o Myaac e tiver o config.local é preciso ser removido (pois ele é criado automaticamente).

Você precisa apontar o seu client corretamente para o login.php para funcionar.

Verifique se o banco de dados está corretamente instalado, possa ser que não tenha realizado as migrations e deve tá faltando alguma coluna.
